[package]
name = "ericplane/scribe"
description = "Persistent, fully-typed, automatically-replicated player data for Roblox Luau, built on ProfileStore."
version = "1.0.11"
license = "MIT"
authors = ["ericplane"]
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://ericplane.github.io/Scribe/"
repository = "https://github.com/ericplane/Scribe"
realm = "shared"

include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE", "README.md"]
exclude = ["**"]

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"